# Conda recipe example.
package:
    name: pyugrid
    version: "0.2.0"

source:
    fn: pyugrid-0.2.0.zip
    url:  https://github.com/pyugrid/pyugrid/archive/develop.zip

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - netcdf4
        - scipy

test:
    imports:
        - pyugrid

about:
    home: https://github.com/pyugrid/pyugrid
    license: BSD
    summary: 'A Python API to utilize data written using the unstructured grid UGRID conventions'
